#define RED 0x200000
#define GREEN 0x002000
#define BLUE 0x000020
#define CYAN 0x002020
#define MAGENTA 0x200020
#define YELLOW 0x202000
#define BLACK 0
#define WHITE 0x202020


// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// Pio_WS2812 //
// ---------- //

#define Pio_WS2812_wrap_target 0
#define Pio_WS2812_wrap 3

static const uint16_t Pio_WS2812_program_instructions[] = {
            //     .wrap_target
    0x6221, //  0: out    x, 1            side 0 [2] 
    0x1123, //  1: jmp    !x, 3           side 1 [1] 
    0x1400, //  2: jmp    0               side 1 [4] 
    0xa442, //  3: nop                    side 0 [4] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program Pio_WS2812_program = {
    .instructions = Pio_WS2812_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config Pio_WS2812_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + Pio_WS2812_wrap_target, offset + Pio_WS2812_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/clocks.h"
#include <hardware/pio.h>
PIO pio= pio0;
uint offset;
uint sm=0;
static inline void Pio_WS2812_program_init(PIO pio, uint sm, uint offset, uint pin, float freq) {
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    pio_sm_config c = Pio_WS2812_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, pin);
    sm_config_set_out_shift(&c, false, true, 24);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    int cycles_per_bit = 10;
    float div = clock_get_hz(clk_sys) / (freq * cycles_per_bit);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
void put_pixel(uint32_t pixel_grb) 
{
  pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}
void setup_Pio_WS2812(uint pin) 
{
   // add the program and return its start location 
  offset = pio_add_program(pio, &Pio_WS2812_program);
  //initialse the PIO SM 
  Pio_WS2812_program_init(pio, sm, offset, pin, 800000);
}

#endif

